version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./model.safetensors:/app/model.safetensors
      - ./config.json:/app/config.json
      - ./special_tokens_map.json:/app/special_tokens_map.json
      - ./vocab.txt:/app/vocab.txt
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend