name: XAllergen
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip>=22.0.0
  - numpy>=1.22.0
  - pandas>=1.5.0
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - scipy>=1.8.0
  - pytorch>=1.13.0
  - scikit-learn>=1.0.0
  - pip:
    - streamlit>=1.20.0
    - fair-esm>=2.0.0
    - captum>=0.6.0
    - py3Dmol>=2.0.0
    - plotly>=5.13.0