name: xallergen_app_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - streamlit
  - pytorch
  - watchdog
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - py3Dmol
  - plotly
  - scipy
  - pip
  - pip:
      - git+https://github.com/facebookresearch/esm.git
      - captum
