name: allergen_app_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - streamlit
<<<<<<< HEAD
=======
  - matplotlib
>>>>>>> 2e4eb2b923c6ec4512c1fa47b577d2bd36197c85
  - pytorch
  - numpy
  - joblib
  - xgboost
  - pip
  - pip:
      - git+https://github.com/facebookresearch/esm.git
